"""creating status table

Revision ID: 32202ed0e2e1
Revises: dda6b9b982e8
Create Date: 2025-02-14 06:13:31.617342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '32202ed0e2e1'
down_revision: Union[str, None] = 'dda6b9b982e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('status', sa.String(length=20), nullable=True))
    op.drop_index('ix_status_email', table_name='status')
    op.drop_index('ix_status_username', table_name='status')
    op.create_index(op.f('ix_status_status'), 'status', ['status'], unique=True)
    op.drop_column('status', 'username')
    op.drop_column('status', 'enabled')
    op.drop_column('status', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('status', sa.Column('enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('status', sa.Column('username', mysql.VARCHAR(length=50), nullable=True))
    op.drop_index(op.f('ix_status_status'), table_name='status')
    op.create_index('ix_status_username', 'status', ['username'], unique=True)
    op.create_index('ix_status_email', 'status', ['email'], unique=True)
    op.drop_column('status', 'status')
    # ### end Alembic commands ###
