"""fix

Revision ID: 4099eb008b30
Revises: 272d5ddc7082
Create Date: 2025-02-14 08:26:20.845717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4099eb008b30'
down_revision: Union[str, None] = '272d5ddc7082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quadrant_priority_id', table_name='quadrant_priority')
    op.drop_index('ix_quadrant_priority_priority_name', table_name='quadrant_priority')
    op.drop_table('quadrant_priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quadrant_priority',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('priority_name', mysql.VARCHAR(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_quadrant_priority_priority_name', 'quadrant_priority', ['priority_name'], unique=True)
    op.create_index('ix_quadrant_priority_id', 'quadrant_priority', ['id'], unique=False)
    # ### end Alembic commands ###
