"""Adding duration column

Revision ID: 4b8468812084
Revises: 0d18f53f06bf
Create Date: 2025-02-27 07:26:16.222418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8468812084'
down_revision: Union[str, None] = '0d18f53f06bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('duration', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'duration')
    # ### end Alembic commands ###
