"""Add task created date

Revision ID: 95014bd799f6
Revises: a7aa93b6d05f
Create Date: 2025-02-21 05:00:27.558746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95014bd799f6'
down_revision: Union[str, None] = 'a7aa93b6d05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'assigned_date')
    # ### end Alembic commands ###
