"""fix

Revision ID: a7aa93b6d05f
Revises: d8116f509fa3
Create Date: 2025-02-14 08:28:25.611033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a7aa93b6d05f'
down_revision: Union[str, None] = 'd8116f509fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'assignee',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'assignee',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
